#!/bin/sh

# Fix for w10
if [ -t 1 ]; then
  exec < /dev/tty
fi

# find modified files
FILES=$(git diff --cached --name-only --diff-filter=ACMR ':!.yarn/cache' | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0

# Prettify all modified files
echo "$FILES" | xargs ./node_modules/.bin/prettier --ignore-unknown --write

# Add back the modified/prettified files to staging
echo "$FILES" | xargs git add

exit 0
