name: Build and deploy GH Pages
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - docs/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@v0.17.2
        env:
          # the path from the root of the repo where we should run the zola build command
          BUILD_DIR: docs/tarkov-stash-docs
          # Target branch
          PAGES_BRANCH: docs
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
